### ISSUE TITLE
Improve coverage of tgo tests

### ISSUE THREAD

**Issue by alchemyst** [Stefan-Endres/DWPM-Mixture-Model#10]
Use [coverage](https://coverage.readthedocs.org/en/coverage-4.0.3/) to look at the coverage of your tests, which is not currently 100% in `tgo.py` and write tests which at least cover all the code you have written.

**Comment by Stefan-Endres** [comment]
Coverage report shows near 100% completion, the lines not run are due to the skipped test in the overflow error and the main pass in tgo.py etc.

```
$ coverage2 report
Name           Stmts   Miss  Cover
----------------------------------
tgo.py            60      2    97%
tgo_tests.py      68      3    96%
----------------------------------
TOTAL            128      5    96%

```

Full report: https://www.dropbox.com/sh/1q3q8jtjqotmzqx/AADMH-huncJcX6C2Jvzx8yJ4a?dl=0
