### ISSUE TITLE
Create a README file

### ISSUE THREAD

**Issue by alchemyst** [Stefan-Endres/DWPM-Mixture-Model#12]
Please create a README file which explains what the main entry points to the code base are. I notice there are files called `pure.py` `binary.py` and `nComp.py`, which I assume handle progressively harder problems, but it is not clear how it all fits together. A couple of lines in a README would help anyone to navigate the code a bit better.

**Comment by Stefan-Endres** [comment]
I hope the new crude README will at least alleviate some confusion. I'm leaving this issue open as a reminder to write a better one once the final structure of the project comes together.

**Comment by alchemyst** [comment]
I'm closing this as 573c020c08db5f6cf53088b4e3c01891ca255d79 documents the project as it is now. As long as we keep it current, this is what I was looking for.
