### ISSUE TITLE
Error in math in tgo.py

### ISSUE THREAD

**Issue by alchemyst** [Stefan-Endres/DWPM-Mixture-Model#14]
In [tgo.py](https://github.com/Stefan-Endres/DWPM-Mixture-Model/blob/ea60b0432394af0d3991a7412d6ef4e0ceecc83e/tgo.py#L174):

```
    k_c = numpy.floor((-(ep - 1) + numpy.sqrt((ep - 1.0)--2 + 80.0 * ep))
                      / 2.0)
```

There is a `--2` which I am pretty sure is not supposed to be there. Is it perhaps supposed to be `**2` instead?

**Comment by Stefan-Endres** [comment]
Ah yes thank you, it should be `**2` (this wouldn't have affected the results in nComp.py since a forced `k = 5` option is used in the routines). Fixed with 9f3027a.
