### ISSUE TITLE
Remove clone code

### ISSUE THREAD

**Issue by alchemyst** [Stefan-Endres/DWPM-Mixture-Model#16]
There are quite a few pieces of copy-paste cloning in the code base at the moment. Worse, some of them are not exactly the same and differ in small difficult-to-see ways.

Run [clonedigger](http://clonedigger.sourceforge.net/) on the code and examine the `output.html` file it will create. If there is redundant code which has been superceded by new code, delete the old code. If both clones are still used, combine them to a common function/method.

I recommend that you develop working tests before doing this task.

**Comment by Stefan-Endres** [comment]
Removed core function clone code 1b81424  1c0f3fa.
Remainder of clonedigger output is for similar test function structures which will remain and main call scripts which will be moved to unittests soon, `output.html`:
https://www.dropbox.com/s/orvyp8pgt94klrk/output.html?dl=0
