### ISSUE TITLE
Extend test suite

### ISSUE THREAD

**Issue by alchemyst** [Stefan-Endres/DWPM-Mixture-Model#17]
This is a high priority request. For me to help more in this code base, it is important to have tests which excercise most of the code and automatically check correct outputs. I am having trouble with some of the refactoring I'd like to do because I'm not sure I will notice if I introduce an error.

**Comment by Stefan-Endres** [comment]
With these commits db97285 b0c4a01 01ddb55 the test suite in `test_all.py` cover all the important code used in the simulation, excluding plotting functions. Running 'coverage test_all.py`(or 'coverage2 test_all.py`) should return all 25 tests as OK except for the 1 skipped test in 'tgo_tests.py'.
Coverage report:
https://www.dropbox.com/sh/ub4oakeis66mdv2/AADCwgSn20fGJdUnRHpT9ZuPa?dl=0

**Comment by alchemyst** [comment]
You may want to have a look at nose as a test runner.

## 

This message may contain unintentional errors, as it was typed on a phone
