### ISSUE TITLE
Delete unused code

### ISSUE THREAD

**Issue by alchemyst** [Stefan-Endres/DWPM-Mixture-Model#18]
There are many commented-out pieces of code in the repository. If they are not used anymore, delete them. You can always get them back from the git history. I'm also not sure that all the files in the repository are currently doing something important (see #12). It is important that only working, used code is in the master branch. If you have some other stuff you're playing with that's not yet ready for prime time, use a new branch. If you have some old stuff which was for testing or for a different purpose, delete it.

**Comment by Stefan-Endres** [comment]
2c953ed removed in the extra commented lines in nComp.py . The commented-out code in the test functions will be dealt with after putting them into test structures for issue #17.
