### ISSUE TITLE
Case conflict: nComp_tests.py vs ncomp_tests.py

### ISSUE THREAD

**Issue by alchemyst** [Stefan-Endres/DWPM-Mixture-Model#28]
You currently have two files in the repository with the same name but different casing (see above). You may not be able to see this on your local copy, but you can verify that it is the case by looking at the list of files on [GitHub](https://github.com/Stefan-Endres/DWPM-Mixture-Model). If you have renamed nComp_test.py to ncomp_tests.py you should have done "git mv nComp_test.py ncomp_test.py". The key point is that git is case sensitive with filenames and that the current situation is causing issues with my mac which has a case-insensitive filesystem. Please do "git rm whichever_file_has_wrong_contents" and then if necessary, do "git mv correct_file_contents correct_file_name".

**Comment by Stefan-Endres** [comment]
2a4f71f

**Comment by alchemyst** [comment]
This issue still exists in the linprog branch.

**Comment by alchemyst** [comment]
Solved in a5b1d2b7c86ab1c78efd338e5de54dbaf13caab9
