### ISSUE TITLE
Make testing code always runnable

### ISSUE THREAD

**Issue by alchemyst** [Stefan-Endres/DWPM-Mixture-Model#7]
There are some lines of testing code which are commented out. This is a bad pattern, as the way you would run this code now becomes "uncomment code, run, observe results, comment code again". It is far better to write this code as a separate file which can be run anytime. It is even better to have it written as a [proper test](http://nedbatchelder.com/text/test0.html). This pattern of having code hidden in comments which is to be run by commenting out section is to be avoided in all cases as it causes churn in the version control system.

**Comment by Stefan-Endres** [comment]
Fixed with #21.
